# Generated by Django 4.2.16 on 2025-02-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='apps/home/static/imgs/'),
        ),
    ]
