# Generated by Django 4.2.16 on 2025-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_serviceadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceadmin',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
