# Generated by Django 4.2.16 on 2025-02-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_service_description_serviceadmin_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceadmin',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='serviceadmin',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceadmin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serviceadmin',
            name='time_to_complete',
        ),
    ]
